Revert "Update to 6.8 Flatpak runtime"
There is a pb with Flatpak
/usr/lib/gcc/x86_64-unknown-linux-gnu/14.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /app/lib/x86_64-linux-gnu/libQt6WebEngineCore.so.6.6.2: undefined reference to `icu_73::FieldPosition::~FieldPosition()'

This reverts commit 6388fe6258fb85aaede5263197b16f672854d25d.